spring:
  freemarker:
    check-template-location: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #    password:
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 2  #流速 每秒
            redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
            rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
            key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  hidePackages: com.zgcenv.gateway
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/v2/api-docs

custom:
  swaggerPath: { organization: /organization/**,gateway-admin: /gateway-admin/** }