feign:
  compression:
    request:
      # 开启请求压缩
      enabled: true
      # 设置压缩的数据类型 默认值：text/html,application/xml,application/json
      mime-types: text/html,application/xml,application/json
      # 设置触发压缩的大小下限 默认值：2048
      min-request-size: 2048
  hystrix:
    # 熔断开启
    enabled: true