spring:
  freemarker:
    check-template-location: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #    password:
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1
    timeout: 5000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
    # jpa 配置
  jpa:
    # sql 打印
    show-sql: true
    # 指定生成表名的存储引擎为InnoDBD
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        # the Hibernate entity manager
        globally_quoted_identifiers: true
        # 格式化SQL输出
        format_sql: false
    hibernate:
      # create, create-drop, update, validate
      # 作用主要用于：自动创建、更新、验证数据库表结构
      ddl-auto: validate
    database: mysql
    open-in-view: false
  groovy:
    template:
      check-template-location: false
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  hidePackages: com.zgcenv.gateway
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379