spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #    password:
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1
    timeout: 5000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true