spring:
  freemarker:
    # 在不需要模板的情况下，解决控制台日志警告问题
    check-template-location: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
  # jpa 配置
  jpa:
    # sql 打印
    show-sql: true
    # 指定生成表名的存储引擎为InnoDBD
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        # the Hibernate entity manager
        globally_quoted_identifiers: true
        # 格式化SQL输出
        format_sql: false
    hibernate:
      # create, create-drop, update, validate
      # 作用主要用于：自动创建、更新、验证数据库表结构
      ddl-auto: validate
    database: mysql
    open-in-view: false
  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456
  groovy:
    template:
      check-template-location: false
custom:
  workerId:
  datacenterId:
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  enabled: true